### ISSUE TITLE
Module Not Found Error : No module named 'telepathy'

### ISSUE THREAD

**Issue by ghost** [sugarlabs/paths#10]
````
1718815142.706368 WARNING root: Activity written for Python 2, consider porting to Python 3. /home/user/Activities/paths/PathsActivity.py:13: PyGIWarning: Gtk was imported without specif e import to ensure that the right version gets loaded.
from gi.repository import Gtk
Traceback (most recent call last):
File "/usr/bin/sugar-activity", line 5, in <module>
activityinstance.main()
File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 179, in ma module
import (module_name)
File "/home/user/Activities/paths/PathsActivity.py", line 32, in <module>
import telepathy
ImportError: No module named telepathy
````
After this I ran the command to install telepathy using both 
```pip install telepathy```
```pip3 install telepathy ```
and even
```pip install --no-deps telepathy```
it says 
```no matching distribution for pandas 1.4.2```

**Comment by quozl** [comment]
Has to be ported to GTK 3 first, then Python 3.
